# .streamlit/secrets.toml
# These secrets can be shared publicly

[connections.mysql]
dialect = "mysql"
host = "cyrildeschamps.fr"
port = 3306
database = "pycock_tail"
username = "pycock_tail"
password = "pycock_tail"